<?php

// app/Http/Controllers/Admin/RoadmapController.php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Inertia\Inertia;
use Inertia\Response;

class RoadmapController extends Controller
{
    public function index(): Response
    {
        $phases = [
            [
                'number' => 1,
                'title' => 'Foundation',
                'status' => 'complete',
                'subtitle' => 'Admin panel, brand identity & infrastructure',
                'milestones' => [
                    ['title' => 'Admin panel with full CRUD', 'done' => true],
                    ['title' => 'Brand identity & logo design', 'done' => true],
                    ['title' => 'Database schema & models', 'done' => true],
                    ['title' => 'Task manager with GCal sync', 'done' => true],
                    ['title' => 'Email DNS setup (MX, SPF, DMARC, DKIM)', 'done' => true],
                    ['title' => 'Constructor component library', 'done' => true],
                    ['title' => 'Page animations system', 'done' => true],
                    ['title' => 'Task notes/journal feature', 'done' => true],
                    ['title' => 'Accessibility audit fixes (contrast, aria, labels)', 'done' => true],
                    ['title' => 'Dashboard time filters (quarter/year)', 'done' => true],
                    ['title' => 'Pest test suite (30+ tests)', 'done' => true],
                ],
            ],
            [
                'number' => 2,
                'title' => 'Launch Ready',
                'status' => 'active',
                'subtitle' => 'Content, visuals & business decisions',
                'milestones' => [
                    ['title' => 'Landing page content (why use this, incentives, FAQs)', 'done' => true],
                    ['title' => 'Landing page icon cards & visual polish', 'done' => true],
                    ['title' => 'Student Hall of Fame banner (Canva)', 'done' => true],
                    ['title' => 'Teacher Certificate of Appreciation (Canva)', 'done' => true],
                    ['title' => 'Student Certificate of Achievement — Distinction (Canva)', 'done' => true],
                    ['title' => 'Teacher Appreciation badges 10+/20+/30+ (Canva)', 'done' => true],
                    ['title' => 'Centre code gradient banners on landing page', 'done' => true],
                    ['title' => 'FAQ + Ready to Get Started combined layout', 'done' => true],
                    ['title' => 'Faber Discounts page (4 cards, infographic, detail sections)', 'done' => true],
                    ['title' => 'For Teachers section content & navigation', 'done' => true],
                    ['title' => 'Email templates (Gmail drafts for teacher enquiries)', 'done' => true],
                    ['title' => 'Shared Google Calendars (exam dates & offers)', 'done' => true],
                    ['title' => 'HTML email signature & Gmail settings', 'done' => true],
                    ['title' => 'For Parents page — full content & FAQs', 'done' => true],
                    ['title' => 'For Students page — certificates, Hall of Fame, prize draws', 'done' => true],
                    ['title' => 'Exam Guide — grades explained, what to expect, digital exams', 'done' => true],
                    ['title' => 'Exam Fees page — all fee tables, dates tab, FAQs', 'done' => true],
                    ['title' => 'Incentives page — badges, certificates, prize draws, how it works', 'done' => true],
                    ['title' => 'Teacher Awards page — Bronze/Silver/Gold/Top Award tiers', 'done' => true],
                    ['title' => 'Recognition page — Thank You, Hall of Fame, Top Scorers', 'done' => true],
                    ['title' => 'Syllabuses page — dropdown linking to all Trinity instruments', 'done' => true],
                    ['title' => 'Terms of Use page', 'done' => true],
                    ['title' => 'Privacy Policy page', 'done' => true],
                    ['title' => 'Cookie banner & preferences', 'done' => true],
                    ['title' => 'Contact page with SMTP email', 'done' => true],
                    ['title' => 'About page', 'done' => true],
                    ['title' => 'FAQ page (dedicated, beyond landing page 4)', 'done' => true],
                    ['title' => 'BookingModal — all 4 Trinity systems (DG, F2F C&J, F2F R&P, Theory)', 'done' => true],
                    ['title' => 'Meta tags & Open Graph for social sharing', 'done' => true],
                    ['title' => 'Coming Soon page with logo', 'done' => true],
                    ['title' => 'Prize draw banner on landing page', 'done' => true],
                    ['title' => 'Incentives banner on all public pages', 'done' => true],
                    ['title' => 'Mobile booking modal fixes', 'done' => true],
                    ['title' => 'Nav scroll fixes & hero logo centering', 'done' => true],
                    ['title' => 'Q1 2026 F2F results imported (37 entries)', 'done' => true],
                    ['title' => 'Q1 2026 digital orders + scores imported (34 entries)', 'done' => true],
                    ['title' => 'Pending Results admin page (weekly checklist)', 'done' => true],
                    ['title' => 'Certificate generator in admin panel', 'done' => true],
                    ['title' => 'Session hours tracking page', 'done' => true],
                    ['title' => 'Student Certificate of Achievement — Merit (Canva)', 'done' => false],
                    ['title' => 'Rewards graphic with correct logo', 'done' => false],
                    ['title' => 'Restyle auth pages with brand constructors', 'done' => false, 'description' => 'Sync restyled pages to template repo too'],
                    ['title' => 'QR code redirect system (musicexams.help/go/...)', 'done' => false, 'description' => 'Short redirect routes for QR codes on flyers, certificates, business cards — plus own /links page instead of Linktree'],
                    ['title' => 'Update YouTube channel branding', 'done' => false],
                    ['title' => 'Booking system step-by-step guides', 'done' => false, 'description' => 'Help page showing how to use all 3 Trinity booking systems'],
                    ['title' => 'Domain name & business name', 'done' => false, 'description' => 'Confirm sole trader name with accountant, connect musicexams.help domain'],
                    ['title' => 'SEO audit implementation', 'done' => false, 'description' => 'Full audit already done — apply fixes once domain is live'],
                    ['title' => 'Disable public registration for launch', 'done' => false],
                    ['title' => 'Turn off hibernation', 'done' => false, 'description' => 'Remove sleep mode for musicexams.help at go-live'],
                ],
            ],
            [
                'number' => 3,
                'title' => 'Go Live',
                'status' => 'upcoming',
                'subtitle' => 'Launch to teachers & start marketing',
                'milestones' => [
                    ['title' => 'Create musicExams.help Facebook page', 'done' => false, 'description' => 'Priority — teacher groups are all on Facebook'],
                    ['title' => 'Create musicExams.help LinkedIn page', 'done' => false],
                    ['title' => 'Set up musicExams.help Instagram', 'done' => false],
                    ['title' => 'Set up musicExams.help TikTok', 'done' => false],
                    ['title' => 'Email campaign to inform teachers of new brand', 'done' => false],
                    ['title' => 'First social media content (Search/Outreach/Suggested)', 'done' => false],
                    ['title' => 'Promote centre code 120 across all channels', 'done' => false],
                    ['title' => 'Clean up HubSpot contacts (72 mixed records)', 'done' => false],
                    ['title' => 'Update old flyer QR codes to point to new site', 'done' => false],
                ],
            ],
            [
                'number' => 4,
                'title' => 'Growth',
                'status' => 'upcoming',
                'subtitle' => 'Features, revenue streams & community',
                'milestones' => [
                    ['title' => 'Syllabus finder with teacher comments & voting', 'done' => false, 'description' => 'Browse by instrument + grade, community recommendations — massive USP'],
                    ['title' => 'Affiliate book links per syllabus (10% ebook commission)', 'done' => false],
                    ['title' => 'Campaigns system (Grade 1 Challenge etc.)', 'done' => false],
                    ['title' => 'Offer INSET/CPD training sessions to schools', 'done' => false],
                    ['title' => 'Quarterly prize draw system in admin panel', 'done' => false],
                    ['title' => 'Social media content calendar', 'done' => false],
                    ['title' => 'Issue digital badges to teachers', 'done' => false],
                    ['title' => 'F2F exam day thank you cards (printed)', 'done' => false],
                    ['title' => 'Parent email follow-up flyers (digital candidates)', 'done' => false],
                    ['title' => 'Teacher dashboard content', 'done' => false, 'description' => 'Show teacher their students, results, entries, awards'],
                    ['title' => 'Teacher free webpage profiles', 'done' => false],
                    ['title' => 'Instrument family pages (/brass, /woodwind, etc.)', 'done' => false],
                    ['title' => 'Help wizard / mini AI assistant', 'done' => false],
                    ['title' => 'Email auto-reply automation', 'done' => false],
                    ['title' => 'Weekly/monthly email digest & blog', 'done' => false],
                    ['title' => 'Book ordering guide for teachers', 'done' => false],
                    ['title' => 'Weekly quiz feature', 'done' => false],
                    ['title' => 'Explainer videos (YouTube + HeyGen)', 'done' => false],
                    ['title' => 'Jazz exams content area', 'done' => false],
                    ['title' => 'Diploma exams marketing push', 'done' => false],
                ],
            ],
            [
                'number' => 5,
                'title' => 'Scale',
                'status' => 'upcoming',
                'subtitle' => 'Analytics, expansion & passive income',
                'milestones' => [
                    ['title' => 'Dashboard analytics & reporting', 'done' => false],
                    ['title' => 'Expand teacher network beyond current schools', 'done' => false],
                    ['title' => 'Trinity Centre Finder (admin tool)', 'done' => false],
                    ['title' => 'Faber trade discount book sales (33%)', 'done' => false],
                    ['title' => 'Promote Trinity Access Fund (2027)', 'done' => false],
                    ['title' => 'Admin panel as reusable CRM / potential SaaS', 'done' => false],
                    ['title' => 'Build passive income from digital exam commissions', 'done' => false],
                    ['title' => 'Paid advertising strategy', 'done' => false],
                    ['title' => 'Digital theory exams (12.5% commission)', 'done' => false],
                    ['title' => 'Shared Google Calendars automation', 'done' => false],
                    ['title' => 'Printed certificates via Prodigi API', 'done' => false],
                    ['title' => 'Browser testing (Cypress/Playwright)', 'done' => false],
                ],
            ],
        ];

        return Inertia::render('admin/Roadmap/Index', [
            'phases' => $phases,
        ]);
    }
}
