<?php

// app/Http/Controllers/Admin/RoadmapController.php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Inertia\Inertia;
use Inertia\Response;

class RoadmapController extends Controller
{
    public function index(): Response
    {
        $phases = [
            [
                'number' => 1,
                'title' => 'Foundation',
                'status' => 'complete',
                'subtitle' => 'Admin panel, brand identity & infrastructure',
                'milestones' => [
                    ['title' => 'Admin panel with full CRUD', 'done' => true],
                    ['title' => 'Brand identity & logo design', 'done' => true],
                    ['title' => 'Database schema & models', 'done' => true],
                    ['title' => 'Unified Contacts data model (multi-type pivot, legacy schema dropped)', 'done' => true],
                    ['title' => 'Nightwatch application monitoring live', 'done' => true],
                    ['title' => 'Task manager with GCal sync', 'done' => true],
                    ['title' => 'Email DNS setup (MX, SPF, DMARC, DKIM)', 'done' => true],
                    ['title' => 'Constructor component library', 'done' => true],
                    ['title' => 'Page animations system', 'done' => true],
                    ['title' => 'Task notes/journal feature', 'done' => true],
                    ['title' => 'Accessibility audit fixes (contrast, aria, labels)', 'done' => true],
                    ['title' => 'Dashboard time filters (quarter/year)', 'done' => true],
                    ['title' => 'Pest test suite (30+ tests)', 'done' => true],
                ],
            ],
            [
                'number' => 2,
                'title' => 'Launch Ready',
                'status' => 'complete',
                'subtitle' => 'Content, visuals & business decisions',
                'milestones' => [
                    ['title' => 'Landing page content (why use this, incentives, FAQs)', 'done' => true],
                    ['title' => 'Landing page icon cards & visual polish', 'done' => true],
                    ['title' => 'Student Hall of Fame banner (Canva)', 'done' => true],
                    ['title' => 'Teacher Certificate of Appreciation (Canva)', 'done' => true],
                    ['title' => 'Student Certificate of Achievement — Distinction (Canva)', 'done' => true],
                    ['title' => 'Teacher Appreciation badges 10+/20+/30+ (Canva)', 'done' => true],
                    ['title' => 'Centre code gradient banners on landing page', 'done' => true],
                    ['title' => 'FAQ + Ready to Get Started combined layout', 'done' => true],
                    ['title' => 'Faber Discounts page (4 cards, infographic, detail sections)', 'done' => true],
                    ['title' => 'For Teachers section content & navigation', 'done' => true],
                    ['title' => 'Email templates (Gmail drafts for teacher enquiries)', 'done' => true],
                    ['title' => 'Shared Google Calendars (exam dates & offers)', 'done' => true],
                    ['title' => 'HTML email signature & Gmail settings', 'done' => true],
                    ['title' => 'For Parents page — full content & FAQs', 'done' => true],
                    ['title' => 'For Students page — certificates, Hall of Fame, prize draws', 'done' => true],
                    ['title' => 'Exam Guide — grades explained, what to expect, digital exams', 'done' => true],
                    ['title' => 'Exam Fees page — all fee tables, dates tab, FAQs', 'done' => true],
                    ['title' => 'Incentives page — badges, certificates, prize draws, how it works', 'done' => true],
                    ['title' => 'Teacher Awards page — Bronze/Silver/Gold/Top Award tiers', 'done' => true],
                    ['title' => 'Recognition page — Thank You, Hall of Fame, Top Scorers', 'done' => true],
                    ['title' => 'Syllabuses page — dropdown linking to all Trinity instruments', 'done' => true],
                    ['title' => 'Terms of Use page', 'done' => true],
                    ['title' => 'Privacy Policy page', 'done' => true],
                    ['title' => 'Cookie banner & preferences', 'done' => true],
                    ['title' => 'Contact page with SMTP email', 'done' => true],
                    ['title' => 'About page', 'done' => true],
                    ['title' => 'FAQ page (dedicated, beyond landing page 4)', 'done' => true],
                    ['title' => 'BookingModal — all 4 Trinity systems (DG, F2F C&J, F2F R&P, Theory)', 'done' => true],
                    ['title' => 'Meta tags & Open Graph for social sharing', 'done' => true],
                    ['title' => 'Coming Soon page with logo', 'done' => true],
                    ['title' => 'Prize draw banner on landing page', 'done' => true],
                    ['title' => 'Incentives banner on all public pages', 'done' => true],
                    ['title' => 'Mobile booking modal fixes', 'done' => true],
                    ['title' => 'Nav scroll fixes & hero logo centering', 'done' => true],
                    ['title' => 'Q1 2026 F2F results imported (37 entries)', 'done' => true],
                    ['title' => 'Q1 2026 digital orders + scores imported (34 entries)', 'done' => true],
                    ['title' => 'Pending Results admin page (weekly checklist)', 'done' => true],
                    ['title' => 'Certificate generator in admin panel', 'done' => true],
                    ['title' => 'Session hours tracking page', 'done' => true],
                    ['title' => 'Student Certificate of Achievement — Merit (Canva)', 'done' => true],
                    ['title' => 'Rewards graphic with correct logo', 'done' => true],
                    ['title' => 'Turn off hibernation', 'done' => true, 'description' => 'DB cluster hibernation turned off 25 Apr 2026 for launch weekend; review in 2 months'],
                ],
            ],
            [
                'number' => 3,
                'title' => 'Go Live',
                'status' => 'upcoming',
                'subtitle' => 'Launch to teachers & start marketing',
                'milestones' => [
                    ['title' => 'Create musicExams.help Facebook page', 'done' => true, 'description' => 'Priority — teacher groups are all on Facebook'],
                    ['title' => 'Create musicExams.help LinkedIn page', 'done' => true],
                    ['title' => 'Set up musicExams.help Instagram', 'done' => true],
                    ['title' => 'Set up musicExams.help TikTok', 'done' => true],
                    ['title' => 'Email campaign to inform teachers of new brand', 'done' => true, 'description' => 'Rebrand announcement sent 9 May 2026 via HubSpot to all 360 existing teacher subscribers (migrated from Mailchimp). Subject: "New email, new website — but still your Trinity exam contact at centre 120". Communicated new email address (musicexams@musicexams.help), new website (musicexams.help), Hall of Fame, Quarterly Prize Draws, Teacher Appreciation Badges, free teacher dashboard CTA. Full record in ~/Documents/Claude/email-sends-log.md.'],
                    ['title' => 'First social media content (Search/Outreach/Suggested)', 'done' => true, 'description' => 'Launch posts live; weekly Mon-9am automation now drafts ready-to-post Twitter + Facebook closing-date reminders (set up 23 May 2026).'],
                    ['title' => 'Promote centre code 120 across all channels', 'done' => false],
                    ['title' => 'Clean up HubSpot contacts (72 mixed records)', 'done' => false],
                    ['title' => 'Update old flyer QR codes to point to new site', 'done' => false],
                    ['title' => 'QR code redirect system (musicexams.help/go/...)', 'done' => false, 'description' => 'Short redirect routes for QR codes on flyers, certificates, business cards — plus own /links page instead of Linktree'],
                    ['title' => 'Booking system step-by-step guides', 'done' => false, 'description' => 'Help page showing how to use all 3 Trinity booking systems'],
                    ['title' => 'Update YouTube channel branding', 'done' => true],
                    ['title' => 'Domain name & business name', 'done' => true, 'description' => 'Confirm sole trader name with accountant, connect musicexams.help domain'],
                    ['title' => 'SEO audit implementation', 'done' => true, 'description' => 'Sitemap, robots.txt, JSON-LD, OG tags, Twitter cards all in place'],
                    ['title' => 'Meta Pixel + conversion tracking installed (Lead / InitiateCheckout)', 'done' => true, 'description' => 'Pixel ID 2164549404093546 live + verified on prod 16 May 2026. Consent-gated, AAM on. Event mapping lead_form_submit->Lead and booking_click->InitiateCheckout, both passing value:14 GBP.'],
                    ['title' => 'Google Ads negative-keyword list applied (Phase 1 Negatives)', 'done' => true, 'description' => '33 phrase-match negatives created + applied to the Phase 1 campaign 15 May 2026 (past papers, answers, jobs, competing boards, ESOL/English, etc.).'],
                    ['title' => 'Internal-traffic exclusion set up (GA4 filter + Google Ads IP + Meta self-exclusion)', 'done' => true, 'description' => 'Done 19 May 2026. GA4 "Paul\'s IPs" internal-traffic filter (home IPv4 + IPv6) active; matching Google Ads IP exclusion; Meta self-exclusion Custom Audience. NOTE: GA4 filters are not retroactive and this is home-IP-only — see the to-do to finish it.'],
                    ['title' => 'Complete Google advertiser verification', 'done' => false, 'description' => 'Under review since late May 2026; hard deadline 16 June 2026. Banner still showing in Google Ads. Ads stop serving if not completed.'],
                    ['title' => 'Fix GA4 link to Google Ads + auto-tagging', 'done' => false, 'description' => 'Google Ads reported ~124 clicks/week but GA4 only sees ~3 google/cpc sessions landing — paid clicks not attributed (likely link/auto-tagging gap + consent gating). Confirm GA4 Admin -> Product Links -> Google Ads, and auto-tagging ON. Until fixed, paid traffic can\'t be evaluated on-site.'],
                    ['title' => 'Finish internal-traffic exclusion (school IP + production-only GA tag)', 'done' => false, 'description' => 'Add St Anselm\'s WiFi IP to GA4 filter + Google Ads IP exclusions (curl ifconfig.me on school WiFi). Add hostname exclusion for localhost + *.laravel.cloud, or gate the GA tag to APP_ENV=production so dev/staging never load it.'],
                ],
            ],
            [
                'number' => 4,
                'title' => 'Growth',
                'status' => 'upcoming',
                'subtitle' => 'Features, revenue streams & community',
                'milestones' => [
                    ['title' => 'Syllabus finder with teacher comments & voting', 'done' => false, 'description' => 'Browse by instrument + grade, community recommendations — massive USP'],
                    ['title' => 'Affiliate book links per syllabus (10% ebook commission)', 'done' => false],
                    ['title' => 'Campaigns system (Grade 1 Challenge etc.)', 'done' => false],
                    ['title' => 'Offer INSET/CPD training sessions to schools', 'done' => false],
                    ['title' => 'Quarterly prize draw system in admin panel', 'done' => true, 'description' => 'Built and used for Q1 2026. /admin/quarter-end manages the full quarterly cycle: top-scorer awards (4 per quarter, Showstopper + Centre Stage, with tie-splitting), student + teacher prize draws (audited PrizeDraw records), Hall of Fame publication, certificate generation, per-winner email templates with Open in Gmail buttons, and (added 8 May 2026) per-winner workflow tracking checkboxes (Bought / Sent / Cert) backed by top_scorer_workflow table. Q1 2026 closed out 8-9 May 2026 with all certs sent, all gift tokens paid (£130 across 7 winners + Thomas G prize draw winner), and rebrand announcement to teacher base.'],
                    ['title' => 'Social media content calendar', 'done' => true, 'description' => 'Weekly scheduled task (Mon 9am) drafts ready-to-post Twitter + Facebook closing-date reminders pulled from the Trinity Exams calendar; Paul posts them. Set up 23 May 2026.'],
                    ['title' => 'Issue digital badges to teachers', 'done' => false],
                    ['title' => 'F2F exam day thank you cards (printed)', 'done' => false],
                    ['title' => 'Parent email follow-up flyers (digital candidates)', 'done' => false],
                    ['title' => 'Teacher dashboard content', 'done' => false, 'description' => 'Show teacher their students, results, entries, awards'],
                    ['title' => 'Teacher piece-prep tracker (Music Register lite)', 'done' => false, 'description' => 'Free tool inside teacher dashboard — add students, type pieces/scales/supporting tests, set % prepared sliders. Pop-up links to syllabus pages for piece lookup. Workflow stickiness embeds referral code 120 in habit. Free-text MVP first, dynamic dropdowns once Trinity PDF data is ingested. Selling point for paid promotion.'],
                    ['title' => 'Trinity syllabus PDF ingestion', 'done' => false, 'description' => 'Parse Trinity\'s downloadable syllabus PDFs (per instrument/grade) into a structured pieces dataset. Powers v2 of the piece-prep tracker (dynamic filtered dropdowns) and could feed the syllabus finder feature. Includes admin re-ingestion tool for when Trinity updates.'],
                    ['title' => 'Theory exam checklist (lead magnet v2)', 'done' => false, 'description' => 'Sister to the Trinity Exam Checklist (practical) — same template/style but for theory exams. Email-capture lead magnet to drive theory exam bookings.'],
                    ['title' => 'Teacher free webpage profiles', 'done' => false],
                    ['title' => 'Instrument family pages (/brass, /woodwind, etc.)', 'done' => false],
                    ['title' => 'Help wizard / mini AI assistant', 'done' => false],
                    ['title' => 'Email auto-reply automation', 'done' => false],
                    ['title' => 'Weekly/monthly email digest & blog', 'done' => false],
                    ['title' => 'Book ordering guide for teachers', 'done' => false],
                    ['title' => 'Weekly quiz feature', 'done' => false],
                    ['title' => 'Explainer videos (YouTube + HeyGen)', 'done' => false],
                    ['title' => 'Jazz exams content area', 'done' => false],
                    ['title' => 'Diploma exams marketing push', 'done' => false],
                    ['title' => 'Restyle auth pages with brand constructors', 'done' => true, 'description' => 'Sync restyled pages to template repo too'],
                    ['title' => 'Admin Exam Entries — edit row', 'done' => false, 'description' => 'Pencil icon on each row in /admin/exam-entries opens a modal to edit candidate_name, teacher_name, result, score, notes, show_full_name. Replaces the current "go to TablePlus" workaround for fixing wrong names (e.g. "Mei Khoo" → "Alice Jun Mei Khoo"), wrong teacher attributions (parent name in teacher field), or correcting a result/score Trinity reported wrong. Audit-logged. Pest tests covering each editable field.'],
                    ['title' => 'Admin Exam Entries — mark as no-show / cancelled', 'done' => false, 'description' => 'Single-click button on each row that sets notes = \'CANCELLED\' (the existing flag the Quarter End controller already filters on). Replaces the current TablePlus UPDATE workaround used when Trinity confirms a candidate didn\'t submit a video within the 28-day window. Excludes the entry from quarter-end totals, top-scorer awards, prize draws and certificate generation. Pest tests + a confirm modal so it can\'t be clicked accidentally.'],
                    ['title' => 'Split CANCELLED into NO_SHOW vs CANCELLED', 'done' => true, 'description' => 'CANCELLED = true cancellation (refund), excluded everywhere. NO_SHOW = booked + paid + commission earned, no submission — excluded from result-based things (Recognition, top scorers, prize draw, pending-results, certificates) but kept in teacher volume tallies (Bronze/Silver/Gold/Top Award badges) so the teacher still gets credit for the booking. Implemented via ExamEntry::NOTE_CANCELLED / NOTE_NO_SHOW constants and ExamEntry::whereResultPossible() scope. Otis Freese (Q1 2026) updated from CANCELLED → NO_SHOW after shipping. Pest tests cover scope behaviour, Recognition exclusion, pending-results exclusion, prize-draw exclusion, and the previously-broken empty-teacher_name "blank applicant" filter.'],
                    ['title' => 'Teacher prize draw winner visible on /dashboard (signed-in teachers only)', 'done' => true, 'description' => 'Quarterly Teacher Prize Draw card on /dashboard, authenticated only. Winner display rules: school admin → school name (Pulse Music etc.); show_full_name=true on the contact → full name; otherwise → "First L". Quarter dropdown defaults to most recent and always includes the current quarter as "not yet drawn" when undrawn. Pre-draw: live ticket count for the signed-in teacher (counts non-CANCELLED entries against their teacher_name). Pest tests cover school-admin display, consent display, default short-name display, undrawn current quarter, ticket counting (CANCELLED excluded), and dropdown ordering.'],
                    ['title' => 'Teacher signup CTA push — page + emails + nav', 'done' => false, 'description' => 'Currently zero encouragement for teachers to register as users. Result: teachers don\'t know the dashboard exists. Build: (a) hero strip on ForTeachers.vue — "Create your free teacher account — track all your students\' bookings, results and certificates in one place" with primary Sign-up button. (b) Login / Sign up link in the public navbar (currently absent). (c) Soft CTA in the post-booking confirmation email, results-published email, and lead-magnet email — "Want to track this? Create a free account at musicexams.help/register and link your existing entries." Tests cover the nav link rendering and the email mentions.'],
                    ['title' => 'Social-media page for prize-draw winners (Instagram-led)', 'done' => false, 'description' => 'Run a dedicated social account — Instagram first, mirror to Facebook/TikTok where it makes sense — celebrating each quarter\'s prize-draw winners (student £50 token + teacher £50 school token + top-scorer Showstopper / Centre Stage awards). Templated post graphics in Canva (winner\'s first name + grade + instrument + certificate, GDPR rule: first name + initial only unless full-name consent). Each post links back to musicexams.help/recognition. Doubles as ongoing content for paid promotion and as social proof for teachers thinking about signing up. Goal: turn each draw into a small marketing moment instead of a private email exchange.'],
                    ['title' => 'Amazon Incentives API — auto-generate gift cards on award publish', 'done' => false, 'description' => 'Eliminate the manual Amazon eGift card buying loop. When admin clicks "Publish top-scorer awards" on /admin/quarter-end, the system uses the Amazon Incentives API to auto-generate gift cards at the right denominations (up to 4 × £20 top-scorer awards with tie-splitting per Paul\'s £5-minimum rule, + £50 student draw, + £50 teacher draw) and injects the claim URLs into the existing Copy Email / Open Gmail templates so each winner\'s email is fully populated and ready to send. Currently Paul manually buys 7 cards per quarter (~£130) via amazon.co.uk and forwards each link by hand — fiddly and prone to "which link goes to which winner" mismatches. Requires Amazon Business account + Amazon Incentives API access (https://developer.amazon.com/incentives-api). Quarterly time saving: ~30–40 mins; lifetime saving compounds across years of quarters and removes the matching headache. Pest tests cover denomination calculation (sole/2-way/3+ways), API failure fallback (don\'t leave a publish in a half-done state), and the "code injected into template" path.'],
                    ['title' => 'Quarter End — per-winner workflow tracking checkboxes', 'done' => true, 'description' => 'Each top-scorer winner row on /admin/quarter-end gets three manual progress checkboxes — Bought / Sent / Cert — with an "All done" pill when all three are ticked. State persists in the `top_scorer_workflow` table (one row per quarter+year+award_key+winner_full_name so tied winners are tracked independently). Optimistic UI: tick toggles instantly, POSTs in background, rolls back on failure. Solves the "which one was I on?" problem during the 7-8-emails-in-one-session workflow and gives a reliable audit trail. Q1 2026 was the first quarter using it. Future extension: extend to student/teacher prize-draw rows (currently top scorers only) and auto-tick "Bought" when the Amazon Incentives API integration lands. Pest tests cover auth required, create/update behaviour, tied-winner independence, untick, validation rejections, and index prop wiring.'],
                    ['title' => 'Admin constructor audit — bring admin UI up to MyText/MyButton standard', 'done' => false, 'description' => 'Public pages already use the brand constructors (MyTextConstructor, MyButtonConstructor, MyGlassCardConstructor, MyBanner, etc.) consistently. Admin pages are mixed — some use them, some have raw <h1>/<button> with bespoke Tailwind classes. Walk through every page in resources/js/pages/admin/* and replace plain headings + buttons with constructors where natural. Skip complex utility-shaped UI (data tables, drag-and-drop, charts) — those don\'t fit the brand-constructor model. Goal: any future template-cloned app inherits the same admin look without re-styling.'],
                    ['title' => 'Background/queue bulk certificate generation (fix timeout)', 'done' => false, 'description' => 'On Laravel Cloud, "Generate all certs" runs synchronously in one web request and the gateway resets the connection ("upstream connect error... disconnect/reset before headers, connection termination") before PHP finishes. set_time_limit(120) does not help because the proxy times out sooner. Move bulk generation (batchGenerate / batchByEntries) to a queued background job that builds the ZIP with progress polling, or chunk it. Single-student / single-teacher generate is fine and fast — only the bulk path times out, and after a timeout the page loses the "Download all" and falls back to "Generate".'],
                    ['title' => 'Fix cert page teacher progress count (shows 22 of 21 / >100%)', 'done' => false, 'description' => 'Progress exceeds 100% (e.g. "22 of 21 teachers"). NOT the blank-teacher bucket — a SELECT for null/empty teacher_name returned empty (23 May 2026). Most likely an extra teacher group from a teacher_name VARIANT (whitespace/case/format difference — e.g. a candidate imported with a slightly different teacher_name string than their classmates, so groupBy(teacher_name) yields one more group than expected). Investigate with SELECT teacher_name, COUNT(*) GROUP BY teacher_name; then either normalise teacher_name on import (trim/canonicalise) and/or align the progress numerator with the teacher denominator. Cosmetic, not data-corrupting.'],
                ],
            ],
            [
                'number' => 5,
                'title' => 'Scale',
                'status' => 'upcoming',
                'subtitle' => 'Analytics, expansion & passive income',
                'milestones' => [
                    ['title' => 'Dashboard analytics & reporting', 'done' => false],
                    ['title' => 'Expand teacher network beyond current schools', 'done' => false],
                    ['title' => 'Trinity Centre Finder (admin tool)', 'done' => false],
                    ['title' => 'Promote Trinity Access Fund (2027)', 'done' => false],
                    ['title' => 'Admin panel as reusable CRM / potential SaaS', 'done' => false],
                    ['title' => 'Build passive income from digital exam commissions', 'done' => false],
                    ['title' => 'Paid advertising strategy', 'done' => true, 'description' => 'Google Ads (£20/day, "Phase 1 — UK Teachers — Q2 2026") and Meta (£10/day, Custom Audience + 1% UK Lookalike) campaigns live since 16 May 2026 — ~£1,200 over a 10-week plan. Monday read-only performance check automated.'],
                    ['title' => 'Digital theory exams (12.5% commission)', 'done' => false],
                    ['title' => 'Shared Google Calendars automation', 'done' => false],
                    ['title' => 'Printed certificates via Prodigi API', 'done' => false],
                    ['title' => 'Browser testing (Cypress/Playwright)', 'done' => false],
                    ['title' => 'Template repo sync — extract reusable shell to dcTemplate', 'done' => false, 'description' => 'When the next app spins up (Music Register, Piano Tabs, Red Hot Music), clone MooWayMan/dcTemplate fresh — don\'t clone musicexamshelp and strip Trinity-specific bits (carry-over is too messy). For that to work, dcTemplate needs to stay current with the reusable shell: brand constructors (MyTextConstructor, MyButtonConstructor, MyGlassCardConstructor, MyBanner, MyFooter, MySocials, MyAccordionConstructor, MyRunnerListTextInfo), public layout (Navbar, Head, Breadcrumbs, BookingModal pattern), restyled auth pages, generic Contact CRUD (no Trinity types), usePageAnimation composable, brand colour tokens, the Roadmap admin page itself, and Pest base test setup including RoutesTest. NOT in template: anything in ExamEntry/Order/PrizeDraw/TopScorerPublication/Student/Instrument/School models, QuarterEnd/Certificate/ThankYou controllers, exam-related public pages, exam_* migrations, centre 120 references. Audit + push reusable changes to dcTemplate before each new app launch.'],
                ],
            ],
        ];

        return Inertia::render('admin/Roadmap/Index', [
            'phases' => $phases,
        ]);
    }
}
