<?php

// app/Http/Controllers/Admin/RoadmapController.php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Inertia\Inertia;
use Inertia\Response;

class RoadmapController extends Controller
{
    public function index(): Response
    {
        $phases = [
            [
                'number' => 1,
                'title' => 'Foundation',
                'status' => 'complete',
                'subtitle' => 'Admin panel, brand identity & infrastructure',
                'milestones' => [
                    ['title' => 'Admin panel with full CRUD', 'done' => true],
                    ['title' => 'Brand identity & logo design', 'done' => true],
                    ['title' => 'Database schema & models', 'done' => true],
                    ['title' => 'Unified Contacts data model (multi-type pivot, legacy schema dropped)', 'done' => true],
                    ['title' => 'Nightwatch application monitoring live', 'done' => true],
                    ['title' => 'Task manager with GCal sync', 'done' => true],
                    ['title' => 'Email DNS setup (MX, SPF, DMARC, DKIM)', 'done' => true],
                    ['title' => 'Constructor component library', 'done' => true],
                    ['title' => 'Page animations system', 'done' => true],
                    ['title' => 'Task notes/journal feature', 'done' => true],
                    ['title' => 'Accessibility audit fixes (contrast, aria, labels)', 'done' => true],
                    ['title' => 'Dashboard time filters (quarter/year)', 'done' => true],
                    ['title' => 'Pest test suite (30+ tests)', 'done' => true],
                ],
            ],
            [
                'number' => 2,
                'title' => 'Launch Ready',
                'status' => 'complete',
                'subtitle' => 'Content, visuals & business decisions',
                'milestones' => [
                    ['title' => 'Landing page content (why use this, incentives, FAQs)', 'done' => true],
                    ['title' => 'Landing page icon cards & visual polish', 'done' => true],
                    ['title' => 'Student Hall of Fame banner (Canva)', 'done' => true],
                    ['title' => 'Teacher Certificate of Appreciation (Canva)', 'done' => true],
                    ['title' => 'Student Certificate of Achievement — Distinction (Canva)', 'done' => true],
                    ['title' => 'Teacher Appreciation badges 10+/20+/30+ (Canva)', 'done' => true],
                    ['title' => 'Centre code gradient banners on landing page', 'done' => true],
                    ['title' => 'FAQ + Ready to Get Started combined layout', 'done' => true],
                    ['title' => 'Faber Discounts page (4 cards, infographic, detail sections)', 'done' => true],
                    ['title' => 'For Teachers section content & navigation', 'done' => true],
                    ['title' => 'Email templates (Gmail drafts for teacher enquiries)', 'done' => true],
                    ['title' => 'Shared Google Calendars (exam dates & offers)', 'done' => true],
                    ['title' => 'HTML email signature & Gmail settings', 'done' => true],
                    ['title' => 'For Parents page — full content & FAQs', 'done' => true],
                    ['title' => 'For Students page — certificates, Hall of Fame, prize draws', 'done' => true],
                    ['title' => 'Exam Guide — grades explained, what to expect, digital exams', 'done' => true],
                    ['title' => 'Exam Fees page — all fee tables, dates tab, FAQs', 'done' => true],
                    ['title' => 'Incentives page — badges, certificates, prize draws, how it works', 'done' => true],
                    ['title' => 'Teacher Awards page — Bronze/Silver/Gold/Top Award tiers', 'done' => true],
                    ['title' => 'Recognition page — Thank You, Hall of Fame, Top Scorers', 'done' => true],
                    ['title' => 'Syllabuses page — dropdown linking to all Trinity instruments', 'done' => true],
                    ['title' => 'Terms of Use page', 'done' => true],
                    ['title' => 'Privacy Policy page', 'done' => true],
                    ['title' => 'Cookie banner & preferences', 'done' => true],
                    ['title' => 'Contact page with SMTP email', 'done' => true],
                    ['title' => 'About page', 'done' => true],
                    ['title' => 'FAQ page (dedicated, beyond landing page 4)', 'done' => true],
                    ['title' => 'BookingModal — all 4 Trinity systems (DG, F2F C&J, F2F R&P, Theory)', 'done' => true],
                    ['title' => 'Meta tags & Open Graph for social sharing', 'done' => true],
                    ['title' => 'Coming Soon page with logo', 'done' => true],
                    ['title' => 'Prize draw banner on landing page', 'done' => true],
                    ['title' => 'Incentives banner on all public pages', 'done' => true],
                    ['title' => 'Mobile booking modal fixes', 'done' => true],
                    ['title' => 'Nav scroll fixes & hero logo centering', 'done' => true],
                    ['title' => 'Q1 2026 F2F results imported (37 entries)', 'done' => true],
                    ['title' => 'Q1 2026 digital orders + scores imported (34 entries)', 'done' => true],
                    ['title' => 'Pending Results admin page (weekly checklist)', 'done' => true],
                    ['title' => 'Certificate generator in admin panel', 'done' => true],
                    ['title' => 'Session hours tracking page', 'done' => true],
                    ['title' => 'Student Certificate of Achievement — Merit (Canva)', 'done' => true],
                    ['title' => 'Rewards graphic with correct logo', 'done' => true],
                    ['title' => 'Turn off hibernation', 'done' => true, 'description' => 'DB cluster hibernation turned off 25 Apr 2026 for launch weekend; review in 2 months'],
                ],
            ],
            [
                'number' => 3,
                'title' => 'Go Live',
                'status' => 'upcoming',
                'subtitle' => 'Launch to teachers & start marketing',
                'milestones' => [
                    ['title' => 'Create musicExams.help Facebook page', 'done' => true, 'description' => 'Priority — teacher groups are all on Facebook'],
                    ['title' => 'Create musicExams.help LinkedIn page', 'done' => true],
                    ['title' => 'Set up musicExams.help Instagram', 'done' => true],
                    ['title' => 'Set up musicExams.help TikTok', 'done' => true],
                    ['title' => 'Email campaign to inform teachers of new brand', 'done' => false],
                    ['title' => 'First social media content (Search/Outreach/Suggested)', 'done' => false],
                    ['title' => 'Promote centre code 120 across all channels', 'done' => false],
                    ['title' => 'Clean up HubSpot contacts (72 mixed records)', 'done' => false],
                    ['title' => 'Update old flyer QR codes to point to new site', 'done' => false],
                    ['title' => 'QR code redirect system (musicexams.help/go/...)', 'done' => false, 'description' => 'Short redirect routes for QR codes on flyers, certificates, business cards — plus own /links page instead of Linktree'],
                    ['title' => 'Booking system step-by-step guides', 'done' => false, 'description' => 'Help page showing how to use all 3 Trinity booking systems'],
                    ['title' => 'Update YouTube channel branding', 'done' => true],
                    ['title' => 'Domain name & business name', 'done' => true, 'description' => 'Confirm sole trader name with accountant, connect musicexams.help domain'],
                    ['title' => 'SEO audit implementation', 'done' => true, 'description' => 'Sitemap, robots.txt, JSON-LD, OG tags, Twitter cards all in place'],
                ],
            ],
            [
                'number' => 4,
                'title' => 'Growth',
                'status' => 'upcoming',
                'subtitle' => 'Features, revenue streams & community',
                'milestones' => [
                    ['title' => 'Syllabus finder with teacher comments & voting', 'done' => false, 'description' => 'Browse by instrument + grade, community recommendations — massive USP'],
                    ['title' => 'Affiliate book links per syllabus (10% ebook commission)', 'done' => false],
                    ['title' => 'Campaigns system (Grade 1 Challenge etc.)', 'done' => false],
                    ['title' => 'Offer INSET/CPD training sessions to schools', 'done' => false],
                    ['title' => 'Quarterly prize draw system in admin panel', 'done' => false],
                    ['title' => 'Social media content calendar', 'done' => false],
                    ['title' => 'Issue digital badges to teachers', 'done' => false],
                    ['title' => 'F2F exam day thank you cards (printed)', 'done' => false],
                    ['title' => 'Parent email follow-up flyers (digital candidates)', 'done' => false],
                    ['title' => 'Teacher dashboard content', 'done' => false, 'description' => 'Show teacher their students, results, entries, awards'],
                    ['title' => 'Teacher piece-prep tracker (Music Register lite)', 'done' => false, 'description' => 'Free tool inside teacher dashboard — add students, type pieces/scales/supporting tests, set % prepared sliders. Pop-up links to syllabus pages for piece lookup. Workflow stickiness embeds referral code 120 in habit. Free-text MVP first, dynamic dropdowns once Trinity PDF data is ingested. Selling point for paid promotion.'],
                    ['title' => 'Trinity syllabus PDF ingestion', 'done' => false, 'description' => 'Parse Trinity\'s downloadable syllabus PDFs (per instrument/grade) into a structured pieces dataset. Powers v2 of the piece-prep tracker (dynamic filtered dropdowns) and could feed the syllabus finder feature. Includes admin re-ingestion tool for when Trinity updates.'],
                    ['title' => 'Theory exam checklist (lead magnet v2)', 'done' => false, 'description' => 'Sister to the Trinity Exam Checklist (practical) — same template/style but for theory exams. Email-capture lead magnet to drive theory exam bookings.'],
                    ['title' => 'Teacher free webpage profiles', 'done' => false],
                    ['title' => 'Instrument family pages (/brass, /woodwind, etc.)', 'done' => false],
                    ['title' => 'Help wizard / mini AI assistant', 'done' => false],
                    ['title' => 'Email auto-reply automation', 'done' => false],
                    ['title' => 'Weekly/monthly email digest & blog', 'done' => false],
                    ['title' => 'Book ordering guide for teachers', 'done' => false],
                    ['title' => 'Weekly quiz feature', 'done' => false],
                    ['title' => 'Explainer videos (YouTube + HeyGen)', 'done' => false],
                    ['title' => 'Jazz exams content area', 'done' => false],
                    ['title' => 'Diploma exams marketing push', 'done' => false],
                    ['title' => 'Restyle auth pages with brand constructors', 'done' => true, 'description' => 'Sync restyled pages to template repo too'],
                    ['title' => 'Admin Exam Entries — edit row', 'done' => false, 'description' => 'Pencil icon on each row in /admin/exam-entries opens a modal to edit candidate_name, teacher_name, result, score, notes, show_full_name. Replaces the current "go to TablePlus" workaround for fixing wrong names (e.g. "Mei Khoo" → "Alice Jun Mei Khoo"), wrong teacher attributions (parent name in teacher field), or correcting a result/score Trinity reported wrong. Audit-logged. Pest tests covering each editable field.'],
                    ['title' => 'Admin Exam Entries — mark as no-show / cancelled', 'done' => false, 'description' => 'Single-click button on each row that sets notes = \'CANCELLED\' (the existing flag the Quarter End controller already filters on). Replaces the current TablePlus UPDATE workaround used when Trinity confirms a candidate didn\'t submit a video within the 28-day window. Excludes the entry from quarter-end totals, top-scorer awards, prize draws and certificate generation. Pest tests + a confirm modal so it can\'t be clicked accidentally.'],
                    ['title' => 'Split CANCELLED into NO_SHOW vs CANCELLED', 'done' => false, 'description' => 'Today \'CANCELLED\' is overloaded — it correctly excludes from Recognition / top scorers / prize draw, but it ALSO drops the entry from teacher volume tallies (10+/20+/30+ award badges) where it shouldn\'t. The teacher booked the exam, Paul earned commission, Trinity collected the fee — the teacher shouldn\'t lose a tally point because the student fluffed the submission. Fix: introduce NO_SHOW as a separate notes value. Recognition / top scorers / prize draw filters exclude BOTH. Teacher volume awards exclude only CANCELLED. Migrate Otis Freese (Q1 2026) from CANCELLED → NO_SHOW once shipped.'],
                    ['title' => 'Teacher prize draw winner visible on /dashboard (signed-in teachers only)', 'done' => true, 'description' => 'Quarterly Teacher Prize Draw card on /dashboard, authenticated only. Winner display rules: school admin → school name (Pulse Music etc.); show_full_name=true on the contact → full name; otherwise → "First L". Quarter dropdown defaults to most recent and always includes the current quarter as "not yet drawn" when undrawn. Pre-draw: live ticket count for the signed-in teacher (counts non-CANCELLED entries against their teacher_name). Pest tests cover school-admin display, consent display, default short-name display, undrawn current quarter, ticket counting (CANCELLED excluded), and dropdown ordering.'],
                    ['title' => 'Teacher signup CTA push — page + emails + nav', 'done' => false, 'description' => 'Currently zero encouragement for teachers to register as users. Result: teachers don\'t know the dashboard exists. Build: (a) hero strip on ForTeachers.vue — "Create your free teacher account — track all your students\' bookings, results and certificates in one place" with primary Sign-up button. (b) Login / Sign up link in the public navbar (currently absent). (c) Soft CTA in the post-booking confirmation email, results-published email, and lead-magnet email — "Want to track this? Create a free account at musicexams.help/register and link your existing entries." Tests cover the nav link rendering and the email mentions.'],
                    ['title' => 'Social-media page for prize-draw winners (Instagram-led)', 'done' => false, 'description' => 'Run a dedicated social account — Instagram first, mirror to Facebook/TikTok where it makes sense — celebrating each quarter\'s prize-draw winners (student £50 token + teacher £50 school token + top-scorer Showstopper / Centre Stage awards). Templated post graphics in Canva (winner\'s first name + grade + instrument + certificate, GDPR rule: first name + initial only unless full-name consent). Each post links back to musicexams.help/recognition. Doubles as ongoing content for paid promotion and as social proof for teachers thinking about signing up. Goal: turn each draw into a small marketing moment instead of a private email exchange.'],
                ],
            ],
            [
                'number' => 5,
                'title' => 'Scale',
                'status' => 'upcoming',
                'subtitle' => 'Analytics, expansion & passive income',
                'milestones' => [
                    ['title' => 'Dashboard analytics & reporting', 'done' => false],
                    ['title' => 'Expand teacher network beyond current schools', 'done' => false],
                    ['title' => 'Trinity Centre Finder (admin tool)', 'done' => false],
                    ['title' => 'Faber trade discount book sales (33%)', 'done' => false],
                    ['title' => 'Promote Trinity Access Fund (2027)', 'done' => false],
                    ['title' => 'Admin panel as reusable CRM / potential SaaS', 'done' => false],
                    ['title' => 'Build passive income from digital exam commissions', 'done' => false],
                    ['title' => 'Paid advertising strategy', 'done' => false],
                    ['title' => 'Digital theory exams (12.5% commission)', 'done' => false],
                    ['title' => 'Shared Google Calendars automation', 'done' => false],
                    ['title' => 'Printed certificates via Prodigi API', 'done' => false],
                    ['title' => 'Browser testing (Cypress/Playwright)', 'done' => false],
                ],
            ],
        ];

        return Inertia::render('admin/Roadmap/Index', [
            'phases' => $phases,
        ]);
    }
}
